language: generic
sudo: false

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  # Fix cask (See https://github.com/cask/cask/issues/399#issuecomment-331640427)
  - perl -ibak -lape 's{#!/usr/bin/env python}{#!/usr/bin/python}' "$(which cask)"
  - evm install $EVM_EMACS --use --skip
  - cask emacs --version
  - make deps

env:
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis

script:
  - make check
